account/urls.py
from django.urls import path
from .forms import LoginForm
from django.contrib.auth import views

urlpatterns = [
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

departamento/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from sistema.settings import BASE_DIR
from . import views, ajax

urlpatterns = [
    #URLs Model Departamento
    path('departamento/<int:pagina>/', views.departamento_view, name='departamento'),
    path('departamento/remover/<int:id>/', views.departamento_remover, name='departamento_remover'),

    #URLs Model Funcionario
    path('funcionario/<int:pagina>/', views.funcionario_view, name='funcionario'),
    path('funcionario/remover/<int:id>/', views.funcionario_remover, name='funcionario_remover'),
    path('funcionario/editarform_ajax/', ajax.funcionario_edit_form_ajax, name='funcionario_edit_form_ajax'),

    #Ajax URL
    path('departamento/ajax/view', ajax.departamento_view_ajax, name='departamento_view_ajax'),
    path('funcionario/ajax/add/',ajax.funcionario_add_ajax, name='funcionario_ajax_add'),
    path('funcionario/ajax/edit/<int:id>',ajax.funcionario_edit_ajax, name='funcionario_ajax_edit'),

    path('departamento/ajax/add/',ajax.departamento_add_ajax, name='departamento_ajax_add'),
    path('departamento/ajax/edit/',ajax.departamento_edit_ajax, name='departamento_ajax_edit'),
    path('departamento/ajax/deletar',ajax.departamento_ajax_deletar, name='departamento_ajax_deletar'),
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

from sistema.settings import BASE_DIR

from account.views import index as home_index

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('departamento/', include('departamento.urls')),
    path('dispositivo/', include('dispositivo.urls')),
    path('inventario/', include('inventario.urls')),
    path('administracao/', include('administracao.urls')),
    path('', home_index, name='home'),

]

departamento/models.py
from django.db import models
from django.db.models.deletion import CASCADE


# Choices models e forms 

CHOICES_PREDIOS = [
    ('Prefeitura Arapoti', 'Prefeitura Municipal de Arapoti'),
    ('Col. Clotário', 'Colégio Clortário Portugal'),
    ('Col. Tel.Carneiro', 'Colégio Telemaco Carneiro'),
    ('Col. D.Zizi', 'Colégio Dona Zizi'),
    ('Col. Romana Kluppel', 'Colégio Romana Carneiro Kluppel'),
    ('Col. Dezidério', 'Colégio Deziderio J. Correa'),
    ('Col. Orlando Pinto', 'Colégio Orlando Pinto - Calógeras'),
    ('PACAA Guarda Mirim', 'PACAA - Guarda Mirim'),
    ('UBS Jd.Aratinga', 'UBS Aratinga Santa Rita'),
    ('UBS Jd.Ceres', 'UBS Jardim Ceres'),
    ('UBS Vila Romana', 'UBS Vila Romana'),
    ('UBS Alphaville', 'UBS Alphaville'),
    ('UBS Calogeras', 'UBS Calógeras'),
    ('CRAS', 'CRAS'),
    ('CAPS', 'CAPS - Centro de Atenção Psicossocial'),
    ('CREAS', 'CREAS - Centro de Referência Especializado em Assistência Social')
]

class Departamento(models.Model):

    predio = models.CharField(max_length=255, null=False, choices=CHOICES_PREDIOS)
    departamento = models.CharField(max_length=255, null=False)
    singla_departamento = models.CharField(max_length=5, default='-', blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)


    def __str__(self) -> str:
        return f'{self.sigla_departamento} - {self.predio}'

    @property
    def sigla_departamento(self) -> str:
        if len(self.singla_departamento) >= 1:
            return self.singla_departamento
        else:
            return self.departamento


class Funcionario(models.Model):
    nome = models.CharField(max_length=255, null=False)
    sobrenome = models.CharField(max_length=255, blank=True, null=True)
    departamento = models.ForeignKey('Departamento', related_name='funcionario',default=1, null=False, on_delete=CASCADE)
    admin_rede = models.CharField(verbose_name='Administrador Rede', max_length=10, default="Não", null=False, choices=(
        ("Sim", 'Sim'),
        ("Não", 'Não')
    ), help_text='Possui privilégios de administrador na rede.')
    usuario_pc = models.CharField(max_length=50, verbose_name="Usuário PC", null=True, blank=True)
    senha_pc = models.CharField(max_length=50, verbose_name='Senha PC', blank=True, null=True)
    controle_acesso = models.CharField(max_length=20, verbose_name='Acesso Proxy', default='Pessimista', choices=[
        ('Pessimista', 'Pessimista'),
        ('Otimista', 'Otimista')
    ],
    help_text='Controle de acesso a sites rede. Pessimista: Controle rígido; Otimista: Pouco controle.')
    descricao = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        if self.sobrenome:
            return f'{self.nome} - {self.departamento.sigla_departamento}'
        else:
            return f'{self.nome} - {self.departamento.sigla_departamento}'
    

departamento/forms.py
from django import forms
from django.forms import widgets
from django.forms.fields import CharField
from django.forms.widgets import Select, SelectMultiple, TextInput, Textarea
from django.db.models import Value as V
from django.db.models.functions import Concat
from .models import Departamento, Funcionario, CHOICES_PREDIOS
from dispositivo.models import CHOICES_SISTEMS

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = ['predio', 'departamento', 'singla_departamento', 'descricao']

    predio = forms.ChoiceField(label='Prédio', choices=CHOICES_PREDIOS, widget=Select(attrs={'class': 'form-control'}))
    departamento = forms.CharField(max_length=255, widget=TextInput(attrs={'class': 'form-control', 'autocomplete':'off', 'placeholder': 'Exemplo: Informática'}))
    singla_departamento = forms.CharField(label='Sigla Departamento', max_length=5, widget=TextInput(attrs={'class': 'form-control', 'autocomplete':'off', 'placeholder':'Exemplo: TI'}), required=False)
    descricao = forms.CharField(label='Descrição', max_length=1000, widget=Textarea(attrs={'rows':'3','class':'form-control', 'autocomplete':'off', 'placeholder': 'Informações Complementares...'}), required=False)


class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = [
            'nome', 'sobrenome', 'departamento', 'admin_rede', 'usuario_pc', 'senha_pc',
            'controle_acesso', 'descricao'
        ]

    nome = forms.CharField(label="Nome *" ,widget=TextInput(attrs={'class': 'form-control', 'autocomplete':'off', 'placeholder': 'Exemplo: Fulano'}))
    sobrenome = forms.CharField(label='Sobrenome', required=False, max_length=255, widget=TextInput(attrs={'class': 'form-control', 'autocomplete':'off', 'placeholder': 'Ex: Silva'}))
    departamento = forms.ModelChoiceField(label='Departamento', queryset=(Departamento.objects.all()), widget=Select(attrs={'class': 'form-control'}))
    usuario_pc = forms.CharField(label='Usuário PC' ,widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: fulano.silva'}), required=False)
    senha_pc = forms.CharField(label='Senha PC', max_length=255, widget=TextInput(attrs={'class': 'form-control', 'autocomplete':'off', 'placeholder': 'Ex: Brasil2021'}), required=False)
    
    controle_acesso = forms.ChoiceField(choices=(
        ('Pessimista', 'Pessimista'),
        ('Otimista','Otimista')
        ),widget=Select(attrs={'class': 'form-control'}))

    admin_rede = forms.ChoiceField(choices=(
        ('Não', 'Não'),
        ("Sim",'Sim')
        ),widget=Select(attrs={'class': 'form-control'}))
    
    descricao = forms.CharField(label="Descrição", max_length=1000, widget=Textarea(attrs={'rows':'3','class':'form-control', 'autocomplete':'off', 'placeholder': 'Informações complementares sobre o usuário.'}), required=False)


class FuncionarioVisualizarForm(forms.Form):
    nome_rede = forms.CharField(label='Nome Rede', max_length=20, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder':'Exemplo: PRE-01'}))
    usuario_pc = forms.CharField(label='Usuário PC', max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder':'Ex: gustavo.silva'}))
    senha_pc = forms.CharField(label='Senha PC', max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder':'Ex: Brasil2021'}))
    sistema_op = forms.ChoiceField(choices=CHOICES_SISTEMS, widget=Select(attrs={'class': 'form-control'}))
    admin_rede = forms.ChoiceField(required=True, choices=(
        ('Não', 'Não'),
        ('Sim', 'Sim')
    ), widget=Select(attrs={'class': 'form-control'}))
    acesso_rede = forms.ChoiceField(choices=(
        ('Pessimista', 'Pessimista'),
        ('Otimista', 'Otimista')
    ), widget=Select(attrs={'class':'form-control'}))

departamento/views.py
from django.core import paginator
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required, permission_required

import departamento
from .models import Departamento, Funcionario
from .forms import DepartamentoForm, FuncionarioForm, FuncionarioVisualizarForm
from django.db.models import Q, F
from django.core.paginator import Paginator
from dispositivo.models import Computador, Impressora, Roteador

@login_required
@permission_required('departamento.view_departamento', raise_exception=True)
def departamento_view(request, pagina=1):
    """Função Responsavel pelo template de listar os departamentos. """
    pesquisa = request.GET.get('query')
    departamentos_list = Departamento.objects.all()
    if pesquisa != '' and pesquisa is not None:
        departamentos_list = departamentos_list.filter(
            Q(departamento__icontains=pesquisa) | Q(predio__icontains=pesquisa) | Q(singla_departamento__icontains=pesquisa) | Q(id__iexact=pesquisa)
        )
    departamentos = Paginator(departamentos_list.order_by('id'), 10).get_page(pagina)
    content = {
        'departamentos': departamentos,
        'pesquisa': pesquisa,
        'form': DepartamentoForm
    }
    return render(request, template_name='departamento/departamento.html', context=content)


@login_required
@permission_required('departamento.delete_departamento', raise_exception=True)
def departamento_remover(request, id):
    departamento = get_object_or_404(Departamento, pk=id)
    funcionarios = Funcionario.objects.all().filter(departamento=departamento)
    impressoras = Impressora.objects.all().filter(departamento=departamento).delete()
    roteadores = Roteador.objects.all().filter(departamento=departamento).delete()
    computadores = Computador.objects.all().filter(Q(departamento=departamento, funcionario__isnull=True) | Q(funcionario__in=funcionarios)).delete()
    funcionarios.delete()
    departamento.delete()
    return redirect(departamento_view, 1)

@login_required
@permission_required('departamento.view_funcionario', raise_exception=True)
def funcionario_view(request, pagina=1):
    """Função responsável pelo template de listar os usuários """
    pesquisa = request.GET.get('query')
    formFuncionario = FuncionarioForm()
    funcionarios_lista = Funcionario.objects.all()
    if pesquisa != '' and pesquisa is not None:

        funcionarios_lista = funcionarios_lista.filter(
            Q(nome__icontains=pesquisa) | Q(sobrenome__icontains=pesquisa) | Q(departamento__departamento__icontains=pesquisa) | Q(departamento__predio__icontains=pesquisa) | Q(controle_acesso__icontains=pesquisa) | Q(id__iexact=pesquisa) | Q(usuario_pc__icontains=pesquisa) | Q(computador__nome_rede__icontains=pesquisa)
        )

    funcionarios = Paginator(funcionarios_lista.order_by('id'), 15).get_page(pagina)

    content = {
        'funcionarios': funcionarios,
        'pesquisa':pesquisa,
        'formFuncionario': formFuncionario,

    }
    return render(request, template_name='funcionario/funcionario.html', context=content)

@login_required
@permission_required('departamento.delete_funcionario')
def funcionario_remover(request, id):
    funcionario = get_object_or_404(Funcionario, pk=id)
    Computador.objects.all().filter(funcionario=funcionario).delete()
    funcionario.delete()
    return redirect(funcionario_view, 1)

templates/departamento/departamento.html
{% extends 'base_listagem.html' %}
{% load static %}

{% block scripts %}
<script>
    forms_urls = {
        'departamento': '{% url "departamento_ajax_add" %}',
        'editar_departamento': '{% url "departamento_ajax_edit" %}',
        'apagarDepartamento': '{% url "departamento_ajax_deletar" %}',
        'departamento_view_ajax': '{% url "departamento_view_ajax" %}',
    }
    </script>
</script>
{% endblock scripts %}


{% block button_adicionar %}
<button class="btn btn-success fonte-arial" data-bs-toggle='modal' data-bs-target='#modalDepartamento'>
    Adicionar
</button>
{% endblock button_adicionar %}

{% block tabela %}

{% if departamentos %}
{% for departamento in departamentos %}
<div class="row p-1 ps-lg-3 m-0 mt-2 shadow d-flex justify-content-between rounded item-pai" style="font-family: Arial, Helvetica, sans-serif;">
    <div class="col-auto p-0 d-flex align-items-center d-flex justify-content-center ">

        <img class='rounded-circle' style='width:7vh;' src="{% static 'img/patrimonio.png' %}" alt="">
        
    </div>
    <div class="col-10 mt-0 item-filho hidden ms-4 ms-lg-4 p-lg-2">
        <div class="row m-0 p-0">
            <div class="col-12 col-lg-4 mb-lg-2">
                <ul class='list-group'>
                    <li class="list-group-item mt-0 p-0">
                        <b>Nome:</b> {{departamento.departamento}}
                    </li>
                    <li class="list-group-item mt-1 p-0">
                        <b>Prédio:</b>{% if departamento.predio %} {{departamento.predio}}{% else %} Indisponível {% endif %}
                    </li>
                    <li class="list-group-item mt-1 p-0">
                        <b>Sigla:</b>{% if departamento.sigla_departamento %} {{departamento.sigla_departamento}}{% else %} Indisponível {% endif %}
                    </li>
                    <li class="list-group-item mt-1 p-0">
                        <b>Funcionarios:</b> {{departamento.funcionario.count}}
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-4">
                <ul class='list-group'>
                    <li class="list-group-item mt-1 p-0">
                        <b>Impressoras:</b> {{departamento.impressora.count}}
                    </li>
                    <li class="list-group-item mt-1  p-0">
                        <b>Roteadores:</b> {{departamento.roteador.count}}
                    </li>
                    
                </ul>
            </div>
            <div class="col-12 col-lg-4">
                <ul class='list-group'>
                    <li class="list-group-item mt-1  p-0">
                        <b>Descricao:</b>
                        {% if departamento.descricao %}
                        {{departamento.descricao}}
                        {% else %}
                        Não possuo nenhuma informação ;c
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col p-0 m-0 ps-3 d-flex justify-content-between">
        <div class='item-esconder'>
            <p class='mb-0 mt-2 '><b>{{departamento.departamento}} </b></p>
            <span class='d-flex d-flex flex-column flex-lg-row mt-1'>
                <p class='mb-1 mt-0'>Prédio: {{departamento.predio}}</p>
            </span>
        </div>
        <span class='d-flex flex-column d-flex flex-lg-row d-flex align-items-center p-lg-2 d-flex d-flex justify-content-center'>
            <i class="fas fa-trash-alt text-black pe-1  pe-lg-3 mb-2 mb-lg-0" onclick='ShowModalDeletarDepartamento(`{% url "departamento_remover" departamento.id %}`)'></i>
            <i class="fas fa-edit text-black" onclick="ShowModalEditDepartamento(`{% url 'departamento_ajax_edit' %}`, '{{departamento.id}}')"></i>
        </span>
    </div>
</div>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-12 shadow p-3">
        <h5 class='fonte-arial text-center'>Nada encontrado</h5>
    </div>
</div>
{% endif %}
{% endblock tabela %}

{% block modals %}
<div class="modal fade" tabindex="-1" id='modalDepartamento'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <span class="modal-title">
                    <h5 class='text-light'><i class="far fa-building pe-3"></i>Adicionar Novo Departamento</h5>
                </span>
                <span data-bs-dismiss='modal'>
                    <i class="fas fa-times text-light"></i>
                </span>
            </div>
            <div class="modal-body">
                <form id='form-departamento' method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
                <div class="modal-footer">
                    <button class="btn btn-outline-secondary" style='font-family: Arial, Helvetica, sans-serif; color:black;' data-bs-dismiss='modal'>Cancelar</button>
                    <button style='font-family: Arial, Helvetica, sans-serif; color:white;' class="btn btn-success" onclick="FormularioDepartamento()">Adicionar</button>
                </div>
            </div>
        </div>        
    </div>
</div>

<div class="modal fade" tabindex="-1" id='modalEditDepartamento'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h5 class="modal-title text-light">
                    <i class="fas fa-pen pe-2"></i>
                    Editar Departamento
                </h5>
                <span data-bs-dismiss='modal'>
                    <i class="fas fa-times text-light"></i>
                </span>
            </div>
            <div class="modal-body">
                <form method='POST' id='form-departamento'>
                    {% csrf_token %}
                    <input type="hidden" id='id_id' name='id' value='0'>
                    <div class="form-group">
                        <label for="id_predio" class='text-black'>Prédio *:</label>
                        {{form.predio}}
                    </div>
                    <div class="form-group mt-2">
                        <label for="id_departamento">Departamento *:</label>
                        {{form.departamento}}
                    </div>
                    <div class="form-group mt-2">
                        <label for="id_singla_departamento">Sigla Departamento</label>
                        {{form.singla_departamento}}
                    </div>
                    <div class="form-group mt-2">
                        <label for="id_descricao">Complemento</label>
                        {{form.descricao}}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-secondary" style='font-family: Arial, Helvetica, sans-serif; color:black;' data-bs-dismiss='modal'>Cancelar</button>
                <button id='btnEditar' class="btn bg-success fonte-arial text-light" onclick='EditarItem("departamento")'>Editar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" id='modalDeletar'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-danger text-light" style="font-family: Arial, Helvetica, sans-serif;">
                <h5>
                    <i class="fas fa-trash-alt"></i>
                    Deseja apagar esse departamento?
                </h5>
                <span data-bs-dismiss='modal'>
                    <i class="fas fa-times text-light"></i>
                </span>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger">
                    Caso você remova esse Departamento, não será possivel adicionar ou remover elementos. Além disso, toda e qualquer informação vinculada a esse departamento será perdida.
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-secondary" style='font-family: Arial, Helvetica, sans-serif; color:black;' data-bs-dismiss='modal'>Cancelar</button>
                <a id='link-rm' href="{% url 'departamento_remover' 1%}" class="btn" style='font-family: Arial, Helvetica, sans-serif; background-color:rgb(238, 37, 37); color:white;'>Apagar</a>
            </div>
        </div>
    </div>
</div>

{% endblock modals %}

{% block nav_paginacao %}
    {% if departamentos.has_previous %}
    <li class="page-item text-dark fonte-arial text-decoration-none"><a class="page-link" href="{% url 'departamento' departamentos.previous_page_number %}{% if pesquisa %}?query={{ pesquisa }}{% endif %}">Voltar</a></li>
    {% endif %}
    {% if departamentos.has_other_pages %}
    <li class="page-item active text-dark fonte-arial text-decoration-none"><a class="page-link"  href="#">{{ departamentos.number }}</a></li>
    {% endif %}
    {% if departamentos.has_next %}
    <li class="page-item text-dark fonte-arial text-decoration-none"><a class="page-link" href="{% url 'departamento' departamentos.next_page_number %}{% if pesquisa %}?query={{ pesquisa }}{% endif %}">Next</a></li>
    {% endif %}
{% endblock nav_paginacao %}

templates/departamento/novo_departamento.html
{% extends 'base.html' %}


{% block title %}
    Novo Departamento
{% endblock title %}

{% block corpo %}
<style>
    body {
        background-color:rgb(235, 232, 232);
    }
    #primeiro {
        margin-top: 150px;
        font-family: 'Times New Roman', Times, serif;
    }

    /* Responsive */
    @media (min-width: 992px) {
        #primeiro {
            margin-top: 100px;
        }
    }
    @media (min-width: 1200px) {
        #primeiro {
            margin-top: 100px;
        }
    }
</style>
<main>
    <div class="container" id='primeiro'>
        <div class="container-fluid" >
            {% if mensagens %}
            <div class="alert alert-danger" role='alert'>
                {% for value in mensagens %}
                    {{ value }}
                {% endfor %}
            </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class='form-label' for="id_predio">Prédio *</label>
                    {{ form.predio }}
                </div>
                <div class="form-group mt-2">
                    <label class='form-label' for="id_predio">Departamento *</label>
                    {{ form.departamento }}
                </div>
                <div class="form-group mt-2">
                    <label class='form-label' for="id_predio">Sigla departamento</label>
                    {{ form.singla_departamento }}
                </div>
                <div class="form-group mt-2">
                    <label class='form-label' for="id_predio">Complemento</label>

                    <p>{{ form.descricao }}</p>
                </div>
                <div class="d-flex justify-content-end mt-3">
                    <button class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</main>

{% endblock corpo %}